[{
    created_at: 'Sun Dec 04 05:39:32 +0000 2016',
    id: 805285386104795100,
    id_str: '805285386104795136',
    text: 'RT @ShaunKing: Reminder. Billy Bush rightfully got fired for laughing at Donald Trump bragging about sexually assaulting women. Trump got e…',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 780752777756540900,
        id_str: '780752777756540928',
        name: 'Katie Shiro',
        screen_name: 'kshiro5',
        location: 'Chicago, IL',
        description: 'Former teacher turned Junior Developer. In my spare time, I like playing ultimate, reading, and exploring Chicago!',
        url: 'https://t.co/YCf9kJcNel',
        entities: [Object],
        protected: true,
        followers_count: 18,
        friends_count: 169,
        listed_count: 0,
        created_at: 'Tue Sep 27 12:55:42 +0000 2016',
        favourites_count: 21,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 8,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '000000',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/780752777756540928/1474981980',
        profile_link_color: '1B95E0',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: false,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
        created_at: 'Sat Dec 03 16:49:04 +0000 2016',
        id: 805091494222823400,
        id_str: '805091494222823424',
        text: 'Reminder. Billy Bush rightfully got fired for laughing at Donald Trump bragging about sexually assaulting women. Tr… https://t.co/zHfU4AIr6y',
        truncated: true,
        entities: [Object],
        source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: true,
        quoted_status_id: 784523974822682600,
        quoted_status_id_str: '784523974822682624',
        quoted_status: [Object],
        retweet_count: 2390,
        favorite_count: 3493,
        favorited: false,
        retweeted: true,
        possibly_sensitive: false,
        lang: 'en'
    },
    is_quote_status: true,
    quoted_status_id: 784523974822682600,
    quoted_status_id_str: '784523974822682624',
    retweet_count: 2390,
    favorite_count: 0,
    favorited: false,
    retweeted: true,
    lang: 'en'
}, {
    created_at: 'Thu Nov 17 04:40:45 +0000 2016',
    id: 799109998467051500,
    id_str: '799109998467051520',
    text: 'RT @BuzzFeed: Bernie Sanders is demanding Trump fire “racist” Steve Bannon https://t.co/bKwH6oa3m2 https://t.co/a8pjPDcuyu',
    truncated: false,
    entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [Object],
        urls: [Object],
        media: [Object]
    },
    extended_entities: { media: [Object] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 780752777756540900,
        id_str: '780752777756540928',
        name: 'Katie Shiro',
        screen_name: 'kshiro5',
        location: 'Chicago, IL',
        description: 'Former teacher turned Junior Developer. In my spare time, I like playing ultimate, reading, and exploring Chicago!',
        url: 'https://t.co/YCf9kJcNel',
        entities: [Object],
        protected: true,
        followers_count: 18,
        friends_count: 169,
        listed_count: 0,
        created_at: 'Tue Sep 27 12:55:42 +0000 2016',
        favourites_count: 21,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 8,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '000000',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/780752777756540928/1474981980',
        profile_link_color: '1B95E0',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: false,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
        created_at: 'Thu Nov 17 00:01:36 +0000 2016',
        id: 799039750854230000,
        id_str: '799039750854230016',
        text: 'Bernie Sanders is demanding Trump fire “racist” Steve Bannon https://t.co/bKwH6oa3m2 https://t.co/a8pjPDcuyu',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        source: '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1187,
        favorite_count: 1709,
        favorited: false,
        retweeted: true,
        possibly_sensitive: false,
        lang: 'en'
    },
    is_quote_status: false,
    retweet_count: 1187,
    favorite_count: 0,
    favorited: false,
    retweeted: true,
    possibly_sensitive: false,
    lang: 'en'
}, {
    created_at: 'Fri Nov 11 00:18:34 +0000 2016',
    id: 796869693478932500,
    id_str: '796869693478932480',
    text: 'RT @esheikh_: Tell Michelle to run #ThankObamaIn4Words \n https://t.co/jWGADQ8Bqk',
    truncated: false,
    entities: {
        hashtags: [Object],
        symbols: [],
        user_mentions: [Object],
        urls: [],
        media: [Object]
    },
    extended_entities: { media: [Object] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 780752777756540900,
        id_str: '780752777756540928',
        name: 'Katie Shiro',
        screen_name: 'kshiro5',
        location: 'Chicago, IL',
        description: 'Former teacher turned Junior Developer. In my spare time, I like playing ultimate, reading, and exploring Chicago!',
        url: 'https://t.co/YCf9kJcNel',
        entities: [Object],
        protected: true,
        followers_count: 18,
        friends_count: 169,
        listed_count: 0,
        created_at: 'Tue Sep 27 12:55:42 +0000 2016',
        favourites_count: 21,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 8,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '000000',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/780752777756540928/1474981980',
        profile_link_color: '1B95E0',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: false,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
        created_at: 'Thu Nov 10 00:59:44 +0000 2016',
        id: 796517662868275200,
        id_str: '796517662868275201',
        text: 'Tell Michelle to run #ThankObamaIn4Words \n https://t.co/jWGADQ8Bqk',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 2913,
        favorite_count: 4643,
        favorited: false,
        retweeted: true,
        possibly_sensitive: false,
        lang: 'en'
    },
    is_quote_status: false,
    retweet_count: 2913,
    favorite_count: 0,
    favorited: false,
    retweeted: true,
    possibly_sensitive: false,
    lang: 'en'
}, {
    created_at: 'Thu Nov 10 13:25:24 +0000 2016',
    id: 796705319380521000,
    id_str: '796705319380520960',
    text: 'RT @TheEllenShow: Thank you @HillaryClinton for your speech and for your endless bravery. We are stronger together.',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 780752777756540900,
        id_str: '780752777756540928',
        name: 'Katie Shiro',
        screen_name: 'kshiro5',
        location: 'Chicago, IL',
        description: 'Former teacher turned Junior Developer. In my spare time, I like playing ultimate, reading, and exploring Chicago!',
        url: 'https://t.co/YCf9kJcNel',
        entities: [Object],
        protected: true,
        followers_count: 18,
        friends_count: 169,
        listed_count: 0,
        created_at: 'Tue Sep 27 12:55:42 +0000 2016',
        favourites_count: 21,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 8,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '000000',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/780752777756540928/1474981980',
        profile_link_color: '1B95E0',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: false,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
        created_at: 'Wed Nov 09 17:14:14 +0000 2016',
        id: 796400519791026200,
        id_str: '796400519791026176',
        text: 'Thank you @HillaryClinton for your speech and for your endless bravery. We are stronger together.',
        truncated: false,
        entities: [Object],
        source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 15695,
        favorite_count: 86924,
        favorited: false,
        retweeted: true,
        lang: 'en'
    },
    is_quote_status: false,
    retweet_count: 15695,
    favorite_count: 0,
    favorited: false,
    retweeted: true,
    lang: 'en'
}, {
    created_at: 'Sun Oct 23 23:13:31 +0000 2016',
    id: 790330338740404200,
    id_str: '790330338740404224',
    text: 'RT @Cubs: The Chicago Cubs are going to the World Series! #FlyTheW https://t.co/Yj36tJCTCn',
    truncated: false,
    entities: {
        hashtags: [Object],
        symbols: [],
        user_mentions: [Object],
        urls: [],
        media: [Object]
    },
    extended_entities: { media: [Object] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 780752777756540900,
        id_str: '780752777756540928',
        name: 'Katie Shiro',
        screen_name: 'kshiro5',
        location: 'Chicago, IL',
        description: 'Former teacher turned Junior Developer. In my spare time, I like playing ultimate, reading, and exploring Chicago!',
        url: 'https://t.co/YCf9kJcNel',
        entities: [Object],
        protected: true,
        followers_count: 18,
        friends_count: 169,
        listed_count: 0,
        created_at: 'Tue Sep 27 12:55:42 +0000 2016',
        favourites_count: 21,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 8,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '000000',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/780752777756540928/1474981980',
        profile_link_color: '1B95E0',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: false,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
        created_at: 'Sun Oct 23 02:45:25 +0000 2016',
        id: 790021279906619400,
        id_str: '790021279906619392',
        text: 'The Chicago Cubs are going to the World Series! #FlyTheW https://t.co/Yj36tJCTCn',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        source: '<a href="http://adobe.com" rel="nofollow">Adobe® Social</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 24533,
        favorite_count: 24307,
        favorited: true,
        retweeted: true,
        possibly_sensitive: false,
        lang: 'en'
    },
    is_quote_status: false,
    retweet_count: 24533,
    favorite_count: 0,
    favorited: true,
    retweeted: true,
    possibly_sensitive: false,
    lang: 'en'
}, {
    created_at: 'Thu Oct 13 13:11:29 +0000 2016',
    id: 786554957055000600,
    id_str: '786554957055000576',
    text: 'RT @everywhereist: Shooting massacre --&gt; "Don\'t you DARE touch the 2nd Amendment." \n\nWomen denouncing a sexual predator --&gt; "REPEAL THE 19t…',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 780752777756540900,
        id_str: '780752777756540928',
        name: 'Katie Shiro',
        screen_name: 'kshiro5',
        location: 'Chicago, IL',
        description: 'Former teacher turned Junior Developer. In my spare time, I like playing ultimate, reading, and exploring Chicago!',
        url: 'https://t.co/YCf9kJcNel',
        entities: [Object],
        protected: true,
        followers_count: 18,
        friends_count: 169,
        listed_count: 0,
        created_at: 'Tue Sep 27 12:55:42 +0000 2016',
        favourites_count: 21,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 8,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '000000',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/780752777756540928/1474981980',
        profile_link_color: '1B95E0',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: false,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
        created_at: 'Thu Oct 13 02:20:18 +0000 2016',
        id: 786391079012544500,
        id_str: '786391079012544512',
        text: 'Shooting massacre --&gt; "Don\'t you DARE touch the 2nd Amendment." \n\nWomen denouncing a sexual predator --&gt; "REPEAL THE 19th!"\n\n#repealthe19th',
        truncated: false,
        entities: [Object],
        source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 4034,
        favorite_count: 6080,
        favorited: false,
        retweeted: true,
        lang: 'en'
    },
    is_quote_status: false,
    retweet_count: 4034,
    favorite_count: 0,
    favorited: false,
    retweeted: true,
    lang: 'en'
}, {
    created_at: 'Mon Oct 03 22:09:00 +0000 2016',
    id: 783066346988965900,
    id_str: '783066346988965888',
    text: 'Even this Chicago fan can get behind @KingJames after this. \nhttps://t.co/eRMS7DPbM7',
    truncated: false,
    entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [Object],
        urls: [Object]
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 780752777756540900,
        id_str: '780752777756540928',
        name: 'Katie Shiro',
        screen_name: 'kshiro5',
        location: 'Chicago, IL',
        description: 'Former teacher turned Junior Developer. In my spare time, I like playing ultimate, reading, and exploring Chicago!',
        url: 'https://t.co/YCf9kJcNel',
        entities: [Object],
        protected: true,
        followers_count: 18,
        friends_count: 169,
        listed_count: 0,
        created_at: 'Tue Sep 27 12:55:42 +0000 2016',
        favourites_count: 21,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 8,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '000000',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/780752777756540928/1474981980',
        profile_link_color: '1B95E0',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: false,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 2,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en'
}, {
    created_at: 'Fri Sep 30 13:53:56 +0000 2016',
    id: 781854594578120700,
    id_str: '781854594578120708',
    text: 'RT @WhiteHouse: "One of the reasons our country is so proud of this year’s #TeamUSA is that 2016 belonged to America’s women Olympians" —@P…',
    truncated: false,
    entities: {
        hashtags: [Object],
        symbols: [],
        user_mentions: [Object],
        urls: []
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 780752777756540900,
        id_str: '780752777756540928',
        name: 'Katie Shiro',
        screen_name: 'kshiro5',
        location: 'Chicago, IL',
        description: 'Former teacher turned Junior Developer. In my spare time, I like playing ultimate, reading, and exploring Chicago!',
        url: 'https://t.co/YCf9kJcNel',
        entities: [Object],
        protected: true,
        followers_count: 18,
        friends_count: 169,
        listed_count: 0,
        created_at: 'Tue Sep 27 12:55:42 +0000 2016',
        favourites_count: 21,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 8,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '000000',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/804069632084688896/-Fzxp9wE_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/780752777756540928/1474981980',
        profile_link_color: '1B95E0',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: false,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
        created_at: 'Thu Sep 29 16:57:15 +0000 2016',
        id: 781538341099442200,
        id_str: '781538341099442176',
        text: '"One of the reasons our country is so proud of this year’s #TeamUSA is that 2016 belonged to America’s women Olympians" —@POTUS #TeamUSAinDC',
        truncated: false,
        entities: [Object],
        source: '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 258,
        favorite_count: 679,
        favorited: true,
        retweeted: true,
        lang: 'en'
    },
    is_quote_status: false,
    retweet_count: 258,
    favorite_count: 0,
    favorited: true,
    retweeted: true,
    lang: 'en'
}]
Katherines - MacBook - Pro - 2: liri - node - app shirok$
